### ISSUE TITLE
Installer GUI Issues

### ISSUE THREAD

**Issue by autopulated** [ARMmbed/yotta_windows_installer#14]
* first screen headline is a bit weird "yotta - it means build awesome". There's already a yotta tagline in the logo, so this is a bit weird. Maybe better to just say "Install yotta". Similarly on the installation complete page.
 * typo on tip for serial driver option: "**Maker** sure you have..."
 * "yotta 0.1.4" is mentioned repeatedly throughout the installer - we should probably be more clear that isn't yotta's own version number. Perhaps say something like "yotta for windows 0.1.4" or "yotta windows environment 0.1.4"
 * the blue icon/banner thing needs a larger border

**Comment by BlackstoneEngineering** [comment]
PR's welcome!

**Comment by BlackstoneEngineering** [comment]
@autopulated 

Going to release a new revision soon, what changes would you like to see? Ie on the first issue what would you prefer it to say?

**Comment by autopulated** [comment]
Just a simple "Install yotta" would be best I think, and "yotta windows installer 0.1.4".

:+1: Thanks!

**Comment by BlackstoneEngineering** [comment]
fixed here : https://github.com/ARMmbed/yotta_windows_installer/commit/a4f25fbfc56887d4b4086bb1e335ffb95f5aaf9e
