### ISSUE TITLE
Pre-release 0.2.0 adds yotta's python to existing Path

### ISSUE THREAD

**Issue by bridadan** [ARMmbed/yotta_windows_installer#17]
The Pre-release 0.2.0 installer adds yotta's installation of python to my existing Path (without using the Run Yotta shortcut). Is this intended behavior? It took me a while to figure out where all my pip packages had gone.

I would suggest if this is supposed to be a completly virtual environment, we shouldn't modify the existing path at all.

**Comment by BlackstoneEngineering** [comment]
This is intended behavior currently. The Python installation and the virtual environment are completely separate. This is a kludge that is currently in place until I can figure out how to distribute a python virtual environment without the need for python on the host system. Currently I install python globally and then use it to create the yotta ve, which is completely seperate from the global python install. 


Worst case scenario : It updates their 2.7.x python install to the latest version and the user explicitly needed something prior to the latest 2.7.x
Likely Scenario : the installer installs python on the users machine or updates their existing install of 2.7.x to the latest version and everything is just fine.

**Comment by bridadan** [comment]
But it also removed all of my pip packages that I had installed from my path as well. I had to manually remove the yotta/python paths from my system path.

If Python is necessary, is it possible in the future to detect if it is installed on the system first?

**Comment by BlackstoneEngineering** [comment]
OoOoOoh, yes, thats a problem, Its not supposed to do that. I want to look at your setup and see what when wrong.

Currently there are two scenarios.

### Case 1 : you have never installed python before
in this case python is installed to C:\yotta\python or whereever you specify in the yotta installer

### Case 2: You have python 2.7.x already installed
* version is less than 2.7.10
     - your python version is updated to 2.7.10 in its current install location
* version is greater than 2.7.10
    - installer should silently fail, and thats ok, because you already have python and pip installed, which is all thats required to set up the virtual environment

### What you reported
* you already had python installed, so case 2,
* yotta installed python to c:\yotta\python and changed where the python env variable points to (previously c:\python27 or something like that)
    ^^ That shouldnt happen, it should instead update python in its current install location, will need to follow up with you in person and inspect your workspace to see what is happening.

**Comment by BlackstoneEngineering** [comment]
Fixed this by adding a python warning message : https://github.com/ARMmbed/yotta_windows_installer/commit/7213182044c98d5fc6a9ce95f8e5203fb0b7b9a7
