### ISSUE TITLE
Add python scripts required for debugging

### ISSUE THREAD

**Issue by mlnx** [ARMmbed/yotta_windows_installer#7]
- Valinor: https://github.com/ARMmbed/valinor
- pgen: https://github.com/project-generator/project_generator (TBC)
- pyOCD: https://github.com/mbedmicro/pyOCD

**Comment by sg-** [comment]
These should already be installed as with yotta or is there something else needed?

**Comment by BlackstoneEngineering** [comment]
Those 3 programs are already installed along with yotta.

**Comment by mlnx** [comment]
Thanks for confirming. Closing.
