### ISSUE TITLE
yotta and dependencies installed to the wrong python scripts directory

### ISSUE THREAD

**Issue by sg-** [ARMmbed/yotta_windows_installer#8]
When using the installer pip is called before the path is modified with the new python installation location. This installs yotta and dependencies in a users existing installation location rather than the yotta sandbox.

**Comment by BlackstoneEngineering** [comment]
Should be fixed by this commit 
https://github.com/ARMmbed/yotta_windows_installer/commit/06ade5f978ccd8d2f9725bf0f61ee1e771be3458

**Comment by BlackstoneEngineering** [comment]
and then will actualy work with this commit https://github.com/ARMmbed/yotta_windows_installer/commit/9c95564d680299246b870d5bbcf1684d36053f08

**Comment by BlackstoneEngineering** [comment]
Closing this now
